server:
  port: 8081
  servlet:
    context-path: ''

spring:
  datasource:
    url: jdbc:mysql://192.168.43.27:3306/homestay?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: roots
    password: 123@qwe
    resources:
      static-locations: classpath:/MATE-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/;
    thymeleaf:
      cache: false
